---
services:
  postgres:
    image: postgres:15-alpine
    container_name: asminfo-postgres
    environment:
      POSTGRES_DB: asminfo
      POSTGRES_USER: asminfo_user
      POSTGRES_PASSWORD: asminfo_password
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-asminfo_user} -d ${POSTGRES_NAME:-asminfo}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: asminfo-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      DATABASE_URL: postgresql+psycopg2://asminfo_user:asminfo_password@postgres:5432/asminfo
    ports:
      - "8000:8000"
    command: fastapi run

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: asminfo-frontend
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "5173:5173"
    command: npm run dev -- --host



volumes:
  postgres_data:
